import { createHash } from "node:crypto";
import { access, mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { AppDatabase } from "../db/database";
import { SettingsService } from "../config/settingsService";
import { CalibrationObservation } from "../types/domain";
import { PvCalibrationService } from "./pvCalibrationService";

const dynamicImport = new Function("specifier", "return import(specifier)") as (specifier:string)=>Promise<any>;

export class CalibrationArchiveService {
  private timer: NodeJS.Timeout|null=null; private running=false;
  constructor(private readonly dataDir:string, private readonly settings:SettingsService, private readonly db:AppDatabase, private readonly calibration:PvCalibrationService) {}
  start(){void this.runNow().catch(()=>undefined);this.timer=setInterval(()=>void this.runNow().catch(()=>undefined),24*60*60*1000);}
  stop(){if(this.timer)clearInterval(this.timer);this.timer=null;}
  async runNow():Promise<{archived:number;deleted:number;files:string[]}> {
    if(this.running)return {archived:0,deleted:0,files:[]}; this.running=true; const files:string[]=[];
    try {const settings=await this.settings.getSettings();if(!settings.calibration.archiveEnabled)return {archived:0,deleted:0,files};const archiveRoot=path.resolve(this.dataDir,settings.calibration.archiveDirectory);const dataRoot=`${path.resolve(this.dataDir)}${path.sep}`;if(!`${archiveRoot}${path.sep}`.startsWith(dataRoot))throw new Error("Archivverzeichnis muss innerhalb des Datenverzeichnisses liegen.");
      const cutoff=new Date(Date.now()-settings.calibration.rawRetentionDays*86400000).toISOString();const rows=this.db.loadExpiredCalibrationObservations(cutoff);if(!rows.length)return {archived:0,deleted:0,files};
      console.info(`[Archive] Start: ${rows.length} Kalibrierungsmessungen`);const groups=new Map<string,CalibrationObservation[]>();for(const row of rows){const key=row.timestampUtc.slice(0,7);groups.set(key,[...(groups.get(key)??[]),row]);}
      let archived=0,deleted=0;const archivedIds:string[]=[];for(const [month,items] of groups){const [year,mon]=month.split("-");const dir=path.join(archiveRoot,"raw",year,mon);await mkdir(dir,{recursive:true});await access(dir);
        const stamp=new Date().toISOString().replace(/[-:.TZ]/g,"");const final=path.join(dir,`calibration_${year}_${mon}_${stamp}.parquet`);const temp=`${final}.tmp-${process.pid}`;
        try {await this.writeParquet(temp,items,settings.calibration.parquetCompression);const validated=await this.validateParquet(temp,items.map(x=>x.observationId));if(!validated)throw new Error("Parquet-Validierung oder ID-Abgleich fehlgeschlagen");await rename(temp,final);
          const checksum=createHash("sha256").update(await readFile(final)).digest("hex");await writeFile(`${final}.sha256`,`${checksum}  ${path.basename(final)}\n`);
          const aggregates=this.aggregate(items,settings.calibration.aggregationIntervalMinutes);const aggregateDir=path.join(archiveRoot,"aggregated",year);await mkdir(aggregateDir,{recursive:true});const aggregateFile=path.join(aggregateDir,`calibration_${settings.calibration.aggregationIntervalMinutes}min_${year}_${mon}_${stamp}.parquet`);const aggregateTemp=`${aggregateFile}.tmp-${process.pid}`;await this.writeAggregates(aggregateTemp,aggregates,settings.calibration.parquetCompression);if(!(await this.validateRowCount(aggregateTemp,aggregates.length)))throw new Error("Aggregat-Parquet-Validierung fehlgeschlagen");await rename(aggregateTemp,aggregateFile);const aggregateChecksum=createHash("sha256").update(await readFile(aggregateFile)).digest("hex");await writeFile(`${aggregateFile}.sha256`,`${aggregateChecksum}  ${path.basename(aggregateFile)}\n`);for(const aggregate of aggregates)this.db.upsertCalibrationAggregate(aggregate.startTimeUtc,settings.calibration.aggregationIntervalMinutes,this.calibration.getModel().version,aggregate);
          archived+=this.db.markCalibrationArchived(items.map(x=>x.observationId),final);archivedIds.push(...items.map(x=>x.observationId));files.push(final,aggregateFile);
        } catch(error){await rm(temp,{force:true}).catch(()=>undefined);throw error;}}
      // First compact all still-present observations into the DB model, then
      // remove only rows whose Parquet files were validated and committed.
      this.calibration.updateModel(settings);deleted=this.db.deleteArchivedCalibrationObservations(archivedIds);this.db.setCalibrationJobStatus("archive","success",{archived,deleted,files},true);console.info(`[Archive] Erfolgreich: ${archived} archiviert, ${deleted} DB-Zeilen gelöscht`);return {archived,deleted,files};
    }catch(error){this.db.setCalibrationJobStatus("archive","error",{message:error instanceof Error?error.message:String(error)});console.error("[Archive] Fehlgeschlagen; keine unbestätigten Rohdaten gelöscht:",error);throw error;}finally{this.running=false;}
  }
  async validateParquet(filename:string, expectedIds:string[]):Promise<boolean>{const {asyncBufferFromFile,parquetReadObjects}=await dynamicImport("hyparquet");const file=await asyncBufferFromFile(filename);const rows=await parquetReadObjects({file});const ids=new Set(rows.map((r:Record<string,unknown>)=>String(r.observationId)));return rows.length===expectedIds.length&&expectedIds.every(id=>ids.has(id));}
  async rebuildModelFromArchive(){if(this.running)throw new Error("Archivierung oder Modellneuberechnung läuft bereits.");this.running=true;const inserted:string[]=[];try{const settings=await this.settings.getSettings();const root=path.resolve(this.dataDir,settings.calibration.archiveDirectory,"raw");const files=await this.findParquetFiles(root);const {asyncBufferFromFile,parquetReadObjects}=await dynamicImport("hyparquet");for(const filename of files){const rows=await parquetReadObjects({file:await asyncBufferFromFile(filename)});for(const raw of rows){const normalized=Object.fromEntries(Object.entries(raw).map(([k,v])=>[k,v instanceof Date?v.toISOString():typeof v==="bigint"?Number(v):v])) as unknown as CalibrationObservation;normalized.archived=true;if(this.db.insertCalibrationObservation(normalized))inserted.push(normalized.observationId);}}const model=this.calibration.updateModel(settings);this.db.deleteArchivedCalibrationObservations(inserted);this.db.setCalibrationJobStatus("model-rebuild","success",{files:files.length,observations:inserted.length,version:model.version},true);return {model,files:files.length,observations:inserted.length};}catch(error){this.db.deleteArchivedCalibrationObservations(inserted);this.db.setCalibrationJobStatus("model-rebuild","error",{message:error instanceof Error?error.message:String(error)});throw error;}finally{this.running=false;}}
  private async findParquetFiles(root:string):Promise<string[]>{try{const entries=await readdir(root,{withFileTypes:true});const nested=await Promise.all(entries.map(entry=>entry.isDirectory()?this.findParquetFiles(path.join(root,entry.name)):Promise.resolve(entry.isFile()&&entry.name.endsWith(".parquet")?[path.join(root,entry.name)]:[])));return nested.flat();}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return [];throw error;}}
  private async validateRowCount(filename:string,expected:number){const {asyncBufferFromFile,parquetReadObjects}=await dynamicImport("hyparquet");return (await parquetReadObjects({file:await asyncBufferFromFile(filename)})).length===expected;}
  private async writeParquet(filename:string,rows:CalibrationObservation[],codec:string){const {parquetWriteFile}=await dynamicImport("hyparquet-writer");const col=(name:keyof CalibrationObservation,type:string)=>({name,data:rows.map(r=>r[name]??null),type,nullable:true});
    parquetWriteFile({filename,codec,columnData:[col("observationId","STRING"),{name:"timestampUtc",data:rows.map(r=>new Date(r.timestampUtc)),type:"TIMESTAMP"},col("timezone","STRING"),col("irradianceWm2","DOUBLE"),col("actualPvPowerW","DOUBLE"),col("pvEnergyWh","DOUBLE"),col("calibrationRatio","DOUBLE"),col("batteryPowerW","DOUBLE"),col("batteryState","STRING"),col("chargerPowerW","DOUBLE"),col("gridPowerW","DOUBLE"),col("houseConsumptionW","DOUBLE"),col("solarElevationDeg","DOUBLE"),col("solarAzimuthDeg","DOUBLE"),col("temperatureC","DOUBLE"),col("cloudCoverPercent","DOUBLE"),col("weatherCode","INT32"),col("month","INT32"),col("season","STRING"),col("validationReason","STRING"),col("qualityScore","DOUBLE"),col("modelVersion","STRING"),col("schemaVersion","INT32"),{name:"createdAtUtc",data:rows.map(r=>new Date(r.createdAtUtc)),type:"TIMESTAMP"}],kvMetadata:[{key:"schema.version",value:"1"},{key:"units.irradianceWm2",value:"W/m2"},{key:"units.power",value:"W"},{key:"units.energy",value:"Wh"}]});}
  private aggregate(rows:CalibrationObservation[],minutes:number){const groups=new Map<number,CalibrationObservation[]>(),ms=minutes*60000;for(const row of rows){const key=Math.floor(new Date(row.timestampUtc).getTime()/ms)*ms;groups.set(key,[...(groups.get(key)??[]),row]);}const stat=(v:number[])=>{const s=[...v].sort((a,b)=>a-b),mean=v.reduce((a,b)=>a+b,0)/v.length;return {mean,min:s[0],max:s.at(-1)!,median:s.length%2?s[Math.floor(s.length/2)]:(s[s.length/2-1]+s[s.length/2])/2,stdDev:Math.sqrt(v.reduce((n,x)=>n+(x-mean)**2,0)/v.length)};};return [...groups].sort(([a],[b])=>a-b).map(([start,items])=>{const pv=stat(items.map(x=>x.actualPvPowerW)),irr=stat(items.map(x=>x.irradianceWm2)),ratio=stat(items.map(x=>x.calibrationRatio));return {startTimeUtc:new Date(start).toISOString(),endTimeUtc:new Date(start+ms).toISOString(),averagePvPowerW:pv.mean,averageIrradianceWm2:irr.mean,averageCalibrationFactor:ratio.mean,minimumPvPowerW:pv.min,maximumPvPowerW:pv.max,medianPvPowerW:pv.median,standardDeviationPvPowerW:pv.stdDev,observationCount:items.length,rejectedCount:0,averageQuality:items.reduce((n,x)=>n+x.qualityScore,0)/items.length,confidence:this.calibration.getModel().confidence.value,minimumSolarElevationDeg:Math.min(...items.map(x=>x.solarElevationDeg)),maximumSolarElevationDeg:Math.max(...items.map(x=>x.solarElevationDeg)),month:items[0].month,season:items[0].season,modelVersion:this.calibration.getModel().version};});}
  private async writeAggregates(filename:string,rows:ReturnType<CalibrationArchiveService["aggregate"]>,codec:string){const {parquetWriteFile}=await dynamicImport("hyparquet-writer");const keys=Object.keys(rows[0]??{}) as Array<keyof (typeof rows)[number]>;parquetWriteFile({filename,codec,columnData:keys.map(name=>{const sample=rows[0][name];const type=name.endsWith("Utc")?"TIMESTAMP":typeof sample==="number"?(["observationCount","rejectedCount","month"].includes(String(name))?"INT32":"DOUBLE"):"STRING";return {name,data:rows.map(r=>name.endsWith("Utc")?new Date(String(r[name])):r[name]),type};}),kvMetadata:[{key:"schema.version",value:"1"},{key:"aggregation.interval.minutes",value:String((new Date(rows[0].endTimeUtc).getTime()-new Date(rows[0].startTimeUtc).getTime())/60000)}]});}
}
