import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { AppDatabase } from "../db/database";
import { defaultSettings } from "../config/defaultSettings";
import { ConfigStore } from "../config/configStore";
import { SettingsService } from "../config/settingsService";
import { AppSettings, CalibrationObservation, EaseeStatePayload, GrowattOverviewPayload, WeatherContext } from "../types/domain";
import { PvCalibrationService } from "./pvCalibrationService";
import { CalibrationArchiveService } from "./calibrationArchiveService";
import { ChargingController } from "./chargingController";

function settings():AppSettings { const s=structuredClone(defaultSettings);s.location={lat:48.1,lon:12.2};s.pvSystem={installedPeakPowerWp:10000,inverterRatedPowerW:8000,maximumBatteryChargePowerW:5000,maximumBatteryDischargePowerW:5000,arrays:[{id:"south",name:"Süd",peakPowerWp:10000,azimuthDeg:180,tiltDeg:30,moduleCount:20,modulePowerWp:500,stringCount:2,knownShading:""}]};s.calibration.maximumDataAgeSeconds=300;s.calibration.maximumTimestampSkewSeconds=300;return s; }
function growatt(now:Date, battery:"charging"|"discharging"|"idle"="charging", pv=3000, exportW=0):GrowattOverviewPayload {return {captured_at_utc:now.toISOString(),live:{pv_total_power_w:pv,estimated_export_to_grid_w:exportW,estimated_import_from_grid_w:0,estimated_load_power_w:2000},battery:{charge_power_w:battery==="charging"?500:0,discharge_power_w:battery==="discharging"?500:0,battery_power_w:battery==="charging"?-500:battery==="discharging"?500:0,flow_state:battery}};}
function weather(now:Date, day=true, irradiance=500):WeatherContext {return {sunTimes:{sunrise:new Date(now.getTime()-3600000).toISOString(),sunset:new Date(now.getTime()+3600000).toISOString(),solarNoon:now.toISOString(),isDay:day,minutesToSunset:60},currentIrradianceWm2:irradiance,forecast2hIrradianceWm2:irradiance,dailyForecast:[],calibrationFactor:1,calibrationSamples:0,model:null as never,todayEnergyWh:0,tomorrowEnergyWh:0,expectedMaximumPvW:0,currentWeather:{timestampUtc:now.toISOString(),temperatureC:20,cloudCoverPercent:20,weatherCode:1,directNormalIrradianceWm2:600,diffuseRadiationWm2:100},fetchedAt:now.toISOString(),fetchError:null};}
async function fixture(){const dir=await mkdtemp(path.join(os.tmpdir(),"pv-cal-"));const db=new AppDatabase(path.join(dir,"test.db"));const service=new PvCalibrationService(db);return {dir,db,service,async close(){db.close();await rm(dir,{recursive:true,force:true});}};}

for(const state of ["charging","discharging"] as const)test(`Kalibrierung akzeptiert Batterie ${state}`,async()=>{const f=await fixture();try{const now=new Date();const d=f.service.record(settings(),growatt(now,state),null,weather(now),now);assert.equal(d.accepted,true);assert.equal(d.observation?.actualPvPowerW,3000);assert.equal(d.observation?.batteryState,state);}finally{await f.close();}});
test("Batterieentladung wird nicht zur PV-Leistung addiert",async()=>{const f=await fixture();try{const now=new Date();const d=f.service.record(settings(),growatt(now,"discharging",2000),null,weather(now),now);assert.equal(d.observation?.actualPvPowerW,2000);}finally{await f.close();}});
test("neutrale Batterie ohne Last wird als mögliche Abregelung verworfen",async()=>{const f=await fixture();try{const now=new Date();assert.deepEqual(f.service.record(settings(),growatt(now,"idle"),null,weather(now),now).reasons,["possible-curtailment"]);}finally{await f.close();}});
test("Fahrzeugladung gibt Messpunkt frei",async()=>{const f=await fixture();try{const now=new Date();const easee:EaseeStatePayload={chargerId:"x",online:true,charging:true,totalPowerWatts:4000};assert.equal(f.service.record(settings(),growatt(now,"idle"),easee,weather(now),now).accepted,true);}finally{await f.close();}});
test("Netzeinspeisung gibt Messpunkt frei",async()=>{const f=await fixture();try{const now=new Date();assert.equal(f.service.record(settings(),growatt(now,"idle",3000,500),null,weather(now),now).accepted,true);}finally{await f.close();}});
test("Nacht, geringe Strahlung, alte und unplausible Werte werden verworfen",async()=>{const f=await fixture();try{const now=new Date();assert.ok(f.service.record(settings(),growatt(now),null,weather(now,false),now).reasons.includes("outside-daylight"));assert.ok(f.service.record(settings(),growatt(now),null,weather(now,true,10),now).reasons.includes("low-irradiance"));const old=new Date(now.getTime()-600000);assert.ok(f.service.record(settings(),growatt(old),null,weather(old),now).reasons.includes("stale-data"));assert.ok(f.service.record(settings(),growatt(now,"charging",50000),null,weather(now),now).reasons.includes("implausible-pv"));}finally{await f.close();}});
test("doppelte Zeitpaare erzeugen nur einen DB-Datensatz",async()=>{const f=await fixture();try{const now=new Date(),s=settings(),g=growatt(now),w=weather(now);f.service.record(s,g,null,w,now);f.service.record(s,g,null,w,now);assert.equal(f.db.loadCalibrationObservations().length,1);}finally{await f.close();}});
test("mehrere Dachflächen und Wechselrichtergrenze werden berücksichtigt",async()=>{const f=await fixture();try{const s=settings();s.pvSystem.arrays.push({...s.pvSystem.arrays[0],id:"west",name:"West",azimuthDeg:270});s.pvSystem.installedPeakPowerWp=20000;const p=f.service.physicalPower(s,new Date().toISOString(),1000,1000,20,100);assert.ok(p>=0&&p<=8000);}finally{await f.close();}});
test("Anlagenvalidierung erkennt Leistungs- und Winkelabweichungen",async()=>{const f=await fixture();try{const s=settings();s.pvSystem.installedPeakPowerWp=5000;s.pvSystem.arrays[0].azimuthDeg=400;const errors=f.service.validateSystem(s);assert.ok(errors.length>=2);}finally{await f.close();}});

test("Ladecontroller verwendet das prognostizierte Ladefenster",()=>{const s=settings();s.rules.enabled=true;s.rules.minSocPercent=50;const now=new Date();const w=weather(now);w.dailyForecast=[{timestampUtc:now.toISOString(),hour:now.getHours(),irradianceWm2:800,theoreticalPvW:7000,predictedPvW:6500,predictedEnergyWh:1625,usableSurplusW:4500,lowerBoundW:5000,upperBoundW:7500,correctionFactor:.95,confidence:.8,modelVersion:"test",hasDataGap:false,isChargingWindow:false}];const easee:EaseeStatePayload={chargerId:"x",online:true,charging:false,chargerModeCode:2,outputCurrentAmp:0};const g=growatt(now,"charging");g.battery!.bms_soc_percent=.8;const blocked=new ChargingController().evaluate(s,g,easee,w,null);assert.equal(blocked.reason,"Ausserhalb des PV-Ladefensters");w.dailyForecast[0].isChargingWindow=true;const allowed=new ChargingController().evaluate(s,g,easee,w,null);assert.notEqual(allowed.reason,"Ausserhalb des PV-Ladefensters");});

test("Parquet-Archiv wird atomar geschrieben, validiert, bereinigt und neu eingelesen",async()=>{const f=await fixture();try{const s=settings();s.calibration.rawRetentionDays=1;const configDir=path.join(f.dir,"config");const store=new ConfigStore(configDir);await store.ensure();await store.writeJson("settings.json",s);const settingsService=new SettingsService(store);const old=new Date(Date.now()-3*86400000);const obs=f.service.record(s,growatt(old),null,weather(old),old).observation!;assert.ok(obs);const archive=new CalibrationArchiveService(f.dir,settingsService,f.db,f.service);const result=await archive.runNow();assert.equal(result.archived,1);assert.equal(result.deleted,1);assert.equal(f.db.loadCalibrationObservations().length,0);assert.equal((await readFile(result.files[0])).subarray(0,4).toString(),"PAR1");assert.equal(await archive.validateParquet(result.files[0],[obs.observationId]),true);const rebuilt=await archive.rebuildModelFromArchive();assert.equal(rebuilt.observations,1);assert.equal(f.db.loadCalibrationObservations().length,0);await writeFile(path.join(f.dir,"broken.parquet"),"broken");await assert.rejects(()=>archive.validateParquet(path.join(f.dir,"broken.parquet"),[obs.observationId]));}finally{await f.close();}});
